cache:
  save_to_disk_interval: 60 # 60 seconds
  ttl: 60 # 60 seconds
  max_size: 1000 # 1000 key-value pairs
mysql:
  host: databaseteam8.c1coikyuqtk8.us-east-1.rds.amazonaws.com
  user: admin
  password: admin123
  db: twitter
  port: 3306
mongodb:
  host: cluster0.wdgelhd.mongodb.net
  user: bhaveshsharma7895
  password: 12345
  db: Database_team_8